- paas-ce/paas/appengine/requirements.txt
- paas-ce/paas/esb/requirements.txt
- paas-ce/paas/login/requirements.txt
- paas-ce/paas/paas/requirements.txt
- upgrade pyyaml to `5.1` and upgrade requests to `2.21.0`
- Fixes #
> upgrade pyyaml and requests version

- paas-ce/paasagent/etc/build/packages/requirements.txt
- 更新requirements.txt中urllib3版本至1.24.1
- 更新requirements.txt中requests版本至2.21.0
- Fixes #
- 更新的目的是提升软件版本的安全性
> update urllib3 and requests version

- paas-ce/paasagent/etc/build/packages/requirements.txt
- paas_agent update urllib3 and requests version
- Fixes #
> Develop update requirements

- paas-ce/paas/appengine/api/utils.py
- str(sid)，显示转换uuid到str类型，修复升级requests版本带来的兼容问题
- Fixes #
> convert uuid to string type explicitly

- paas-ce/paas/appengine/api/utils.py
- bugfix: appengine request header with uuid
- Fixes #
> Develop fix requests

- paas-ce/paas/paas/templates/app/list.html
- paas-ce/paas/paas/templates/saas/list.html
- update app and saas search tip
- Fixes #
> App search tip

- paas-ce/paas/paas/templates/app/list.html
- paas-ce/paas/paas/templates/saas/list.html
- update app and saas search tip
- Fixes #
> update app and saas search tip

- paas-ce/paas/appengine/api/utils.py
- str(token), 显示转换uuid类型成string, 修复升级requests包引入的兼容问题
- Fixes #
> convert uuid to str explicitly

- paas-ce/paas/appengine/api/utils.py
- str(token), 显示转换uuid类型成string, 修复升级requests包引入的兼容问题
- Fixes #
>  convert uuid to str explicitly

- .gitattributes
> try to ignore the static code stats

- .gitattributes
- try to ignore the static code stats
- Fixes #
> ignore the static code stats

- paas-ce/paasagent/core/http.go
- paas-ce/paasagent/core/utils.go
- paas-ce/paasagent/job/job.go
- paas-ce/paasagent/server/http.go
> Develop add annotation

- paas-ce/paasagent/core/http.go
- paas-ce/paasagent/core/utils.go
- paas-ce/paasagent/job/job.go
- paas-ce/paasagent/server/http.go
> Revert "Develop add annotation"

- paas-ce/paasagent/core/http.go
- paas-ce/paasagent/core/utils.go
- paas-ce/paasagent/job/job.go
- paas-ce/paasagent/server/http.go
> add annotation for paasagent

- paas-ce/paas/login/bkaccount/accounts.py
- fix the too complex of account _is_bk_token_valid
- Fixes #
> fix the too complex of account _is_bk_token_valid

- docs/install/ce_paas_install.md
- paas-ce/paas/esb/components/bk/apisv2/bk_paas/toolkit/configs.py
- paas-ce/paas/esb/configs/default_template.py
- paas-ce/paas/esb/settings.py
- 更新paas部署文档, 完善部署顺序
- 修复 ESB 配置模板中 PAAS_HOST 设置
- Fixes #
> 更新文档及esb配置文件

- docs/install/ce_paas_install.md
- paas-ce/paas/examples/settings/login/settings_production.py
- paas-ce/paas/login/conf/settings_development.py
- paas-ce/paas/login/conf/settings_production.py.sample
- 说明及注释: login/conf中配置文件 `SITE_URL` 在本地开发和生产中不同
- Fixes #
> login settings SITE_URL diff in develoment/production

- docs/install/ce_paas_install.md
- paas-ce/paas/examples/settings/paas/settings_production.py
- paas-ce/paas/paas/conf/settings_development.py
- paas-ce/paas/paas/conf/settings_production.py.sample
- paas-ce/paas/paas/conf/settings_testing.py
- 更新文档, 对本地开发paas配置文件中LOGIN_DOMAIN进行说明
- Fixes #
> update doc: LOGIN_DOMAIN in paas development

- paas-ce/paas/login/urls.py
> fix develop login url 404

- paas-ce/paas/login/urls.py
> Revert "fix develop login url 404"

- docs/install/ce_paas_install.md
- paas-ce/paas/examples/settings/login/settings_production.py
- paas-ce/paas/examples/settings/paas/settings_production.py
- paas-ce/paas/login/conf/settings_development.py
- paas-ce/paas/login/conf/settings_production.py.sample
- paas-ce/paas/paas/conf/settings_development.py
- paas-ce/paas/paas/conf/settings_production.py.sample
- paas-ce/paas/paas/conf/settings_testing.py
- 更新文档, 对本地开发login配置中SITE_URL进行说明
- 更新文档, 对本地开发paas配置文件中LOGIN_DOMAIN进行说明
- Fixes #
> Fix login settings

- docs/install/ce_paas_install.md
- paas-ce/paas/examples/settings/login/settings_production.py
- paas-ce/paas/examples/settings/paas/settings_production.py
- paas-ce/paas/login/conf/settings_development.py
- paas-ce/paas/login/conf/settings_production.py.sample
- paas-ce/paas/login/urls.py
- paas-ce/paas/paas/conf/settings_development.py
- paas-ce/paas/paas/conf/settings_production.py.sample
- paas-ce/paas/paas/conf/settings_testing.py
> 修复本地开发登录URL 404问题

- paas-ce/paas/login/bkaccount/accounts.py
- fix login decrypt_token function bug
- Fixes #
> fix login decrypt token code bug

- paas-ce/paas/esb/components/bk/apis/fta/toolkit/imap.py
- fta imap 拉取邮件问题修复：获取到邮件为空的时候，直接忽略
- Fixes #
> fix fta imap

- paas-ce/paas/paas/templates/guide/newbie.html
> update guide doc of python framework

- paas-ce/paas/paas/templates/base.html
- 变更点(Changes)
修复我的应用-滚动按钮提示内容错误
- 相关issues 
Fixes #97 
- 备注
close: #97
> bugfix: 滚动按钮提示内容错误。issue #97

- paas-ce/paas/paas/templates/app/info.html
- 我的应用 - 应用管理 - 基本信息 - 开发语言-去除Django字样
- Fixes #96
> fixbug:Development Language Change #96

- paas-ce/paas/paas/templates/app_env/home.html
- 修复了issue95 我的应用-应用管理-环境变量title缺失的问题
- Fixes #95
> bugfix:我的应用-应用管理-环境变量title缺失 issue 95

- paas-ce/paas/paas/templates/base_app.html
- 修复我的应用-应用部署-下架 title错误
- Fixes #94
close: #94
> bugfix: 我的应用-应用部署-下架 title错误 (#94)

- paas-ce/paas/paas/resource/migrations/0007_update_python_doc_url.py
- 修改资源下载 python的文档地址
- 删除统一开发环境
- Fixes #
> add resource migration for python doc url and delete united dev-env

- README.md
- README_EN.md
- 修复替换已安装的蓝鲸社区版指引 链接404的问题
- Fixes #
> update link or replace ce with open source version

- paas-ce/paas/paas/templates/release/version.html
<!--
请保证PR标题明确清晰, 易于理解
Keep PR title verbose enough
相关issue可以是 #编号 或者贴 issue链接
https://github.com/Tencent/bk-PaaS/issues/93
- xxxx 当版本历史为空时, 前端出现两条横线
- Fixes #93
> 93:修改BUG：当版本历史为空时, 前端出现两条横线

- paas-ce/paas/paas/app/forms.py
- paas-ce/paas/paas/templates/app/create.html
- paas-ce/paas/paas/templates/app/info.html
- paas-ce/paas/paas/templates/app/list.html
- paas-ce/paas/paas/templates/app/list_table.part
- paas-ce/paas/paas/templates/base.html
- paas-ce/paas/paas/templates/engine/external_server.html
- paas-ce/paas/paas/templates/engine/server.html
- paas-ce/paas/paas/templates/guide/newbie.html
- paas-ce/paas/paas/templates/home/index.html
- paas-ce/paas/paas/templates/saas/info.html
- paas-ce/paas/paas/templates/saas/list.html
- 修复前端css/js没有加`?v={STATIC_VERSION}`导致的问题
- Fixes #
> add static version for css/js

- paas-ce/paas/esb/components/confapis/sops/apidocs/en/import_common_template.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/zh_hans/import_common_template.md
- paas-ce/paas/esb/components/confapis/sops/sops.yaml
- paas-ce/paas/paas/esb/mainsite/templates/mainsite/base.html
- 修复 API网关 用户头像问题
- 新增 sops 组件 import_common_template
> Fix user avatar

- paas-ce/paas/paas/templates/base_center.html
- paas-ce/paas/paas/templates/guide/newbie.html
- fix #128 
- fix #140 
- Fixes #
> Bugfix 0717

- paas-ce/paas/paas/home/constants.py
> use HTTP_SCHEMA for job/cc link int

- paas-ce/paas/paas/templates/saas/info.html
> fix saas info show settings style

- paas-ce/paas/login/bkaccount/accounts.py
- 禁用 bk_language cookie写入;
- Fixes #
> disable bk_language while the i18n is not support in ce

- paas-ce/paas/login/bkaccount/accounts.py
- paas-ce/paas/paas/templates/base_center.html
> fix resource download icon

- paas-ce/paas/paas/saas/utils.py
- 支持smart应用在根路径下放置logo文件
- Fixes #
> support logo file in pkg root dir

- paas-ce/paas/esb/common/constants.py
- paas-ce/paas/esb/components/bk/apisv2/esb/__init__.py
- paas-ce/paas/esb/components/bk/apisv2/esb/apidocs/en/get_components.md
- paas-ce/paas/esb/components/bk/apisv2/esb/apidocs/en/get_systems.md
- paas-ce/paas/esb/components/bk/apisv2/esb/apidocs/zh_hans/get_components.md
- paas-ce/paas/esb/components/bk/apisv2/esb/apidocs/zh_hans/get_systems.md
- paas-ce/paas/esb/components/bk/apisv2/esb/get_components.py
- paas-ce/paas/esb/components/bk/apisv2/esb/get_systems.py
- paas-ce/paas/esb/components/bk/apisv2/esb/toolkit/__init__.py
- paas-ce/paas/esb/components/bk/apisv2/esb/toolkit/configs.py
- paas-ce/paas/esb/components/bk/apisv2/esb/toolkit/tools.py
- paas-ce/paas/esb/components/esb_conf.py
- paas-ce/paas/esb/esb/management/utils/constants.py
【新增】ESB 新增 get_systems/get_components 组件
> add esb get_systems,get_components apis

- paas-ce/paas/esb/components/confapis/sops/apidocs/en/create_task.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/en/get_common_template_info.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/en/get_common_template_list.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/en/get_task_detail.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/en/get_task_node_detail.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/en/node_callback.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/zh_hans/get_common_template_info.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/zh_hans/get_common_template_list.md
- paas-ce/paas/esb/components/confapis/sops/apidocs/zh_hans/node_callback.md
- paas-ce/paas/esb/components/confapis/sops/sops.yaml
> update sops apis

- paas-ce/paas/esb/apps/sdk_management/sdk_tmpl/blueking/component/shortcuts.py
- paas-ce/paas/esb/common/constants.py
- paas-ce/paas/esb/components/component.py
- paas-ce/paas/esb/components/constants.py
- paas-ce/paas/esb/configs/default_template.py
- paas-ce/paas/esb/esb/bkcore/models.py
- paas-ce/paas/esb/esb/management/commands/sync_system_and_channel_data.py
- paas-ce/paas/esb/esb/management/utils/conf_tools.py
- paas-ce/paas/esb/esb/management/utils/constants.py
- paas-ce/paas/esb/settings.py
- 更新API网关系统及文档分类的管理逻辑
- 修复API网关组件系统不存在时，数据初始化异常的问题
> update system/doc-category manage

- paas-ce/paas/esb/requirements.txt
- paas-ce/paas/esb/settings.py
> add enum34 to esb requirements

- paas-ce/lesscode/README.md
> add branch intro

- paas-ce/lesscode/lib/client/src/element-materials/modifier/props/components/render-prop.vue
> feature: 组件属性配置类型提示首字母大写

- paas-ce/lesscode/lib/client/src/common/util.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/props/components/render-prop.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/props/components/strategy/column.vue
> merge manually from #204

- paas-ce/lesscode/lib/client/src/element-materials/materials/charts-line/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/index.vue
- 修复 charts-line options.tips 小问题以及 merge 之前的 fix bug 等等
> 修复 charts-line options.tips 小问题以及 merge 之前的 fix bug 等等

- paas-ce/lesscode/lib/client/src/components/vue-code/code-mixin.js
- paas-ce/lesscode/lib/client/src/views/index/index.vue
> 【lesscode】修复体验问题

- paas-ce/lesscode/lib/client/src/components/render/grid.css
- paas-ce/lesscode/lib/client/src/components/render/grid.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/package.json
- 画布仅剩一个 grid 时，不允许删除
- 增加清空 grid 操作
> 【lesscode】画布仅剩一个 grid 时，不允许删除；增加清空 grid 操作

- paas-ce/lesscode/lib/client/src/App.vue
- paas-ce/lesscode/lib/client/src/css/common.css
- paas-ce/lesscode/lib/client/src/router/index.js
- paas-ce/lesscode/lib/client/src/views/system/index.vue
- paas-ce/lesscode/lib/client/src/views/system/projects.vue
- paas-ce/lesscode/lib/server/app.browser.js
- paas-ce/lesscode/package.json
> 新增项目级别页面布局和项目列表页UI

- paas-ce/lesscode/lib/server/conf/data-base.js.example
> up data-base conf example

- paas-ce/lesscode/lib/server/model/function.js
- paas-ce/lesscode/lib/server/model/sql/20200707/initial.sql
- merge page 
- page 表，content 和 sourceCode 字段改为允许 null
> merge page && page 表，content 和 sourceCode 改为允许 null

- paas-ce/lesscode/lib/client/src/components/project/page-dialog.vue
- paas-ce/lesscode/lib/client/src/views/project/page.vue
- paas-ce/lesscode/lib/server/model/page.js
> page 模块小问题修复

- paas-ce/lesscode/lib/client/src/components/methods/index.vue
- paas-ce/lesscode/lib/client/src/components/methods/label-list.vue
- paas-ce/lesscode/lib/client/src/components/methods/monaco.vue
- paas-ce/lesscode/lib/client/src/router/index.js
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/lib/client/src/views/preview/index.vue
- paas-ce/lesscode/lib/client/src/views/project/function-manage.vue
- paas-ce/lesscode/lib/client/src/views/project/index.vue
- paas-ce/lesscode/lib/client/src/views/system/component-manage/all/components/layout.vue
- paas-ce/lesscode/lib/client/src/views/system/index.vue
- paas-ce/lesscode/lib/server/controller/function.js
- paas-ce/lesscode/lib/server/model/entities/base.js
- paas-ce/lesscode/lib/server/model/project.js
- 使用实时项目id获取函数列表，而不是mock的项目
- 函数相关体验问题优化
> 函数体验优化，对接项目

- paas-ce/lesscode/lib/server/app.browser.js
- paas-ce/lesscode/lib/server/conf/http.js
> merge && cookie

- paas-ce/lesscode/lib/client/src/App.vue
- paas-ce/lesscode/lib/client/src/api/index.js
- paas-ce/lesscode/lib/client/src/views/preview/index.vue
- paas-ce/lesscode/lib/client/src/views/system/account.vue
- paas-ce/lesscode/lib/client/src/views/system/component-manage/index.vue
- paas-ce/lesscode/lib/server/app.browser.js
- paas-ce/lesscode/lib/server/controller/mock-data.js
- paas-ce/lesscode/lib/server/controller/page.js
- paas-ce/lesscode/lib/server/controller/user.js
- paas-ce/lesscode/lib/server/middleware/auth.js
- paas-ce/lesscode/lib/server/middleware/json-send.js
- paas-ce/lesscode/lib/server/model/user.js
- paas-ce/lesscode/lib/server/util.js
- paas-ce/lesscode/package.json
> 登录权限控制 & 账号管理页面 & 用户信息

- paas-ce/lesscode/lib/client/src/custom/x-table/index.vue
- paas-ce/lesscode/lib/server/controller/mock-data.js
- paas-ce/lesscode/lib/server/router/mock-data.js
> 修复自定义组件 x-table 获取数据的问题

- paas-ce/lesscode/lib/client/src/api/index.js
- paas-ce/lesscode/lib/server/controller/user.js
- paas-ce/lesscode/lib/server/middleware/auth.js
> 修复 cookie 中 bktoken 失效的问题

- paas-ce/lesscode/lib/client/src/element-materials/modifier/props/components/strategy/boolean.vue
> 修复属性面板中 switch 组件不会正确渲染的问题

- paas-ce/lesscode/lib/client/src/api/pureAxios.js
- paas-ce/lesscode/lib/client/src/components/methods/funcForm.vue
- paas-ce/lesscode/lib/client/src/components/methods/index.vue
- paas-ce/lesscode/lib/client/src/components/vue-code/code-mixin.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/props/components/strategy/remote.vue
- paas-ce/lesscode/lib/client/src/main.js
- paas-ce/lesscode/lib/client/src/store/index.js
- paas-ce/lesscode/lib/client/src/views/project/function-manage.vue
- 函数提示优化，去掉调用函数的业务逻辑，交由用户自己控制
- 远程数据增加按钮，手动刷新数据
> 函数提示优化，增加按钮获取数据

- paas-ce/lesscode/lib/client/src/components/vue-code/code-mixin.js
> 修复 compId 的问题

- readme.md
- readme_en.md
> add iam project link

- paas2/esb/apps/sdk_management/utils.py
- paas2/esb/common/forms.py
- paas2/esb/esb/management/commands/add_compperm_for_app.py
- paas2/esb/esb/management/commands/check_service.py
- paas2/esb/esb/management/commands/sync_api_docs.py
- paas2/esb/esb/management/commands/sync_system_and_channel_data.py
- paas2/esb/esb/management/commands/update_locale.py
- paas2/esb/esb/outgoing.py
- paas2/esb/esb/utils/func_ctrl.py
- Django command option 定义方式修复
- Django 字符串方法命名修复
- Python2/3 字符差异修复
> 更新 ESB Django 存量引用

- paas2/paas/urls.py
> Ft upgrade py3 test

- paas2/paas/conf/default.py
> update static version

- paas2/paas/home/utils.py
> remove duplicate user apps in list

- paas2/paas/app/initializer.py
> fix string.lowercase not support in python3

- paas2/esb/common/base_loggers.py
- paas2/esb/common/errors.py
- paas2/esb/esb/outgoing.py
- paas2/esb/poetry.lock
- paas2/esb/pyproject.toml
- paas2/esb/requirements_dev.txt
- paas2/esb/tests/common/test_errors.py
- paas2/esb/tests/esb/test_outgoing.py
- 修复 RequestThirdPartyException
- 修复 outgoing 中部分数据编码问题
> 修复 ESB 升级 python3 问题

- paas2/paas/templates/app_log/home.html
> bugfix: export log 500 while use the log_type=diy

- paas2/paas/esb/apps/bootstrapform/templatetags/bootstrap.py
- paas2/paas/esb/apps/guide/views.py
- paas2/paas/esb/apps/manager/utils.py
- paas2/paas/esb/bkcore/models.py
- paas2/paas/esb/common/django_utils.py
- paas2/paas/requirements.txt
> 修复 ESB 管理端升级 python3 问题

- paas2/paas/bk_iam/decorators.py
- paas2/paas/common/utils/basic.py
- paas2/paas/templates/app_esb_auth/esb_sys_api.part
- paas2/paas/templates/app_log/home.html
> iteritems to items for python3

- paas-ce/lesscode/lib/client/src/common/dom-to-image.js
> fix: 页面预览图偶发失败

- paas-ce/lesscode/lib/client/src/components/variable/variable-select.vue
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/sideslider/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/directives/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- 关闭侧栏组件(sideslider)的v-show、v-if配置，以及表达式配置，防止出现使用的错误
> fix: 修复侧栏sideSlider的配置问题

- paas-ce/lesscode/lib/client/src/components/project/edit-route-dialog.vue
- paas-ce/lesscode/lib/client/src/views/project/page-setting.vue
> fix: 页面绑定路由时未禁用已绑定跳转的路由问题

- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/editor/menu/edit.vue
> fix(edit): 路由参数tips

- paas-ce/lesscode/lib/client/src/common/drag-line.js
- paas-ce/lesscode/lib/client/src/common/util.js
- paas-ce/lesscode/lib/client/src/components/render/component.vue
- paas-ce/lesscode/lib/client/src/components/render/free-layout.vue
- paas-ce/lesscode/lib/client/src/components/render/grid.vue
- paas-ce/lesscode/lib/client/src/components/render/index.vue
- paas-ce/lesscode/lib/client/src/components/render/offsetMixin.js
- paas-ce/lesscode/lib/client/src/components/variable/variable-select.vue
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/diff/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/sideslider/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/directives/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- paas-ce/lesscode/lib/client/src/views/index/children/component-panel-mixin.js
- fix: 修复diff组件缺少language报错的问题
- fix: 修复交互式组件中，自由布局定位错误的问题
- fix: 修复交互式组件处于激活态时，底层下仍然可交互的问题
> fix: 修复交互式组件的若干问题

- paas-ce/lesscode/lib/server/model/sql/20210604/update.sql
> feat: add db index sql

- paas-ce/lesscode/lib/client/src/components/variable/variable-select.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/directives/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/lib/server/model/page-code.js
> 画布属性实时获取最新变量值

- paas-ce/lesscode/lib/server/conf/logger-path.js
- paas-ce/lesscode/lib/server/logger.js
> feat: add log path config

- paas-ce/lesscode/lib/client/src/App.vue
> feat: 优化帮助导航

- paas-ce/lesscode/lib/client/src/components/ui/extra-links.vue
> 因优化tooltip显示效果，误删原逻辑判断
-fixed 修复帮助点击无反应问题
> fix: 修复帮助点击无反应问题

- paas2/esb/components/confapis/bk_log/bk_log.yaml
- paas2/esb/esb/component/base.py
> ESB 更新 BK_LOG 配置类组件

- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/editor/menu/edit.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/side-menu/index.vue
> feature(edit): 导航自定义Icon

- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/package.json
- feat: update 复合组件
- fix: 部分页面预览图加载失败的问题
> feat: update 复合组件 && fix: 部分页面预览图加载失败的问题

- paas2/paas/templates/home/index.html
> bugfix: bkdialog js/css missing while do bind weixin

- paas-ce/lesscode/lib/client/src/components/patch/bkCharts/bkCharts.vue
- paas-ce/lesscode/lib/client/src/components/patch/bkCharts/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-bar/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-line/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-pie/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/charts-line/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/charts-pie/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/index.js
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/server/project-template/project-init-code/lib/client/src/components/bkCharts.vue
- paas-ce/lesscode/lib/server/project-template/project-init-code/package.json
- paas-ce/lesscode/package.json
> feature(bk-charts): 添加bkCharts

- paas-ce/lesscode/lib/server/model/page-code.js
- fix: element table el-table-cokumn slot-scope 变量的问题
> fix: element table el-table-cokumn slot-scope 变量的问题

- paas-ce/lesscode/lib/server/controller/page.js
> bugfix: 兼容页面不存在调用页面详情数据

- paas-ce/lesscode/lib/server/conf/system.js
- paas-ce/lesscode/lib/server/controller/page.js
- paas-ce/lesscode/lib/server/model/page.js
- 补充js关键字为无效页面ID
- 删除页面同时删除项目与页面的关联关系
> fix: 补充js关键字为无效页面ID和删除页面同时删除项目与页面的关联关系

- paas-ce/lesscode/lib/client/src/views/system/projects.vue
- paas-ce/lesscode/lib/server/controller/project.js
- paas-ce/lesscode/lib/server/model/project.js
> fix: 项目列表页面项目缩略图为空的问题

- paas-ce/lesscode/lib/client/src/views/changelog/index.md
- paas-ce/lesscode/package.json
> feat: bumo to v0.2.3

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
> bugfix: 修复变量切换

- paas-ce/lesscode/lib/client/src/api/index.js
- paas-ce/lesscode/lib/client/src/api/request-error.js
- paas-ce/lesscode/lib/client/src/common/bkmagic.js
- paas-ce/lesscode/lib/server/custom-global.js
- paas-ce/lesscode/lib/server/middleware/error.js
> perf: api 错误信息处理

- paas-ce/lesscode/lib/client/src/common/bkmagic.js
- paas-ce/lesscode/lib/client/src/components/methods/func-form.vue
- paas-ce/lesscode/lib/client/src/components/methods/index.vue
- paas-ce/lesscode/lib/client/src/components/methods/monaco-func.vue
- paas-ce/lesscode/lib/client/src/components/methods/monaco.vue
- paas-ce/lesscode/lib/client/src/components/variable/variable-form/index.vue
- paas-ce/lesscode/lib/client/src/components/variable/variable-form/variable-code.vue
- paas-ce/lesscode/lib/client/src/store/modules/functions.js
- paas-ce/lesscode/lib/client/src/views/project/function-manage.vue
- paas-ce/lesscode/lib/server/controller/function.js
- paas-ce/lesscode/lib/server/controller/variable.js
- paas-ce/lesscode/lib/server/model/project-code.js
- paas-ce/lesscode/lib/server/project-template/project-init-code/lib/client/src/router/index.js
- paas-ce/lesscode/lib/server/project-template/router-template.js
- paas-ce/lesscode/lib/server/router/function.js
- paas-ce/lesscode/lib/server/util.js
- paas-ce/lesscode/package.json
1. 函数和计算变量添加自动fix eslint
2. 部署页面title和页面名称一致
> 自动fix eslint & 部署页面title

- paas2/esb/components/bk/apisv2/usermanage/fs_list_users.py
- paas2/esb/esb/channel/base.py
- paas2/esb/tests/esb/channel/test_base.py
- 修复 fs_list_users XSS 问题
- fs_list_users 响应添加 staff_status 字段
> 修复 fs_list_users XSS 问题

- paas2/esb/components/bk/apisv2/cc/transfer_host_to_resourcemodule.py
- paas2/release.md
- ESB CC 组件 transfer_host_to_resourcemodule 添加参数 bk_module_id
> ESB CC 组件 transfer_host_to_resourcemodule 添加参数 bk_module_id

- paas-ce/lesscode/lib/client/src/element-materials/materials/element/input/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/element/select/index.js
- paas-ce/lesscode/lib/server/model/page-code.js
- 修复colorpicker组件预览失败问题
- 修复input组件在画布和预览中展示不一问题
- Fixes #375
> bugfix：element ui 组件bug修复

- paas-ce/lesscode/lib/client/src/components/header.vue
> feat: 顶导 设计规范 链接更新

- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/button/index.js
> 按钮组件增加icon设置属性

- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/rate/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/tag-input/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/transfer/index.js
- 表单组件 加上v-model 可以获取表单值
> -  标签输入
> -  穿梭框，获取选择后的列表
> - rate
- Fixes #436
> 【lesscode】表单组件 加上v-model 可以获取表单值

- paas-ce/lesscode/lib/client/src/store/modules/page.js
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/lib/server/controller/page.js
- paas-ce/lesscode/lib/server/model/entities/page.js
- paas-ce/lesscode/lib/server/model/migrations/20210706115827-update-sql.js
- paas-ce/lesscode/lib/server/model/migrations/sqls/20210706115827-update-sql-down.sql
- paas-ce/lesscode/lib/server/model/migrations/sqls/20210706115827-update-sql-up.sql
- paas-ce/lesscode/lib/server/model/sql/20210706/update.sql
- paas-ce/lesscode/lib/server/router/page.js
> feature: 画布加锁功能

- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/rate/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/transfer/index.js
- rate组件添加sync修饰符，修复预览状态下无法变更rate值问题
- 穿梭框组件的target-list属性增加tips
- Fixes #436
> 表单组件 加上v-model 可以获取表单值

- paas2/paas/esb/apps/guide/mdfiles/zh-hans/weixin_component_guide.md
> update weixbin component guide doc

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/text.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/textarea.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/render-config/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/slot.vue
- paas-ce/lesscode/lib/server/controller/db-upgrade-helper.js
> 修改 text & textarea 类型转义

- paas-ce/lesscode/lib/server/controller/db-upgrade-helper.js
> update table type

- paas-ce/lesscode/lib/client/src/element-materials/materials/element/card/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- paas-ce/lesscode/lib/server/controller/db-upgrade-helper.js
- paas-ce/lesscode/lib/server/util.js
- paas-ce/lesscode/package.json
> 修复card组件数据

- paas-ce/lesscode/lib/client/src/components/render/component.vue
- paas-ce/lesscode/lib/client/src/components/render/index.vue
- paas-ce/lesscode/lib/client/src/preview/auth.js
- paas-ce/lesscode/lib/server/controller/db-upgrade-helper.js
> 修改预览错误提示信息

- paas-ce/lesscode/lib/client/src/components/render/component.vue
- paas-ce/lesscode/lib/client/src/components/render/index.vue
> fix: 修复嵌套单元格渲染出错的问题

- paas-ce/lesscode/lib/client/src/element-materials/materials/element/card/index.js
> fix elcard

- paas-ce/lesscode/lib/client/src/element-materials/materials/element/radio-group/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/element/table/index.js
- 修复radio组件默认值不生效问题
- 提供table组件height属性和maxheight属性默认值
- Fixes #375
> bugfix: element组件bug修复

- paas-ce/lesscode/lib/client/src/element-materials/materials/element/table/index.js
- 修改table组件的height属性配置
- Fixes #375
> bugfix: table组件bug修复

- paas-ce/lesscode/lib/client/src/common/targetData.js
> 修复复制造成id重复的问题

- paas-ce/lesscode/lib/client/src/components/render/component.vue
> perf: 优化布局容器渲染逻辑

- paas-ce/lesscode/lib/server/model/page-code.js
- 修复element组件库的radio组件默认值显示有误问题
- Fixes #375
> element组件库的radio组件默认值显示有误

- paas-ce/lesscode/lib/client/src/components/methods/function-helper.js
- paas-ce/lesscode/lib/client/src/components/render/component.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/list/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/render-config/bk/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/render-config/element/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/slot.vue
- paas-ce/lesscode/lib/server/model/page-code.js
> slot 兼容老数据处理

- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/package.json
- fix: 修复自由布局中表格宽度不断增大的问题
- update: bk-magic-vue 升级到最新
> fix: 修复自由布局中表格宽度不断增大的问题

- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-bar/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-bubble/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-line/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-pie/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-radar/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/bk-charts-scatter/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/charts-bar/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/charts-line/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/charts-pie/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/form-item.vue
- 每个组件里，数据源可绑定远程数据的，给出数据示例
- Fixes #433
> 组件开发：远程数据给出数据示例

- paas-ce/lesscode/lib/client/src/components/render/component.vue
- paas-ce/lesscode/lib/client/src/components/render/free-layout.css
- paas-ce/lesscode/lib/client/src/components/render/free-layout.vue
- paas-ce/lesscode/lib/client/src/components/render/grid.css
- paas-ce/lesscode/lib/client/src/components/render/grid.vue
- paas-ce/lesscode/lib/client/src/components/widget/context-menu.vue
- paas-ce/lesscode/lib/client/src/main.js
- paas-ce/lesscode/lib/client/src/views/index/index.css
- 修复拖入交互底色过浅的问题
- 修复右键菜单不消失的问题
- 优化菜单hover颜色，统一为红色
> bugfix: 右键菜单、交互优化

- paas-ce/lesscode/lib/server/model/page-code.js
> fix: 自由布局中宽度限定死的问题

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- fix: 修复对象类型变量，直接 . 引用变量会报错的问题
> fix: 修复对象类型变量，直接 . 引用变量会报错的问题

- paas-ce/lesscode/lib/client/src/views/project/basic.vue
- paas-ce/lesscode/lib/client/src/views/system/projects.vue
- paas-ce/lesscode/lib/server/model/migrations/20210902025823-update-sql.js
- paas-ce/lesscode/lib/server/model/migrations/sqls/20210902025823-update-sql-down.sql
- paas-ce/lesscode/lib/server/model/migrations/sqls/20210902025823-update-sql-up.sql
- paas-ce/lesscode/lib/server/model/page.js
- paas-ce/lesscode/lib/server/model/project.js
- paas-ce/lesscode/lib/server/model/sql/20210901/update.sql
- 项目和页面及函数与组件分类名称区分大小写
- 兼容新的客户端请求错误处理方法
> fix: 使项目和页面及函数与组件分类名称区分大小写

- paas-ce/lesscode/lib/client/src/components/methods/function-helper.js
- fix: 修复函数执行替换变量时，语法错误的问题。利用 acorn 在编译时加上分号，使 js 语法符合预期
> fix: 修复函数执行替换变量时，语法错误的问题。利用 acorn 在编译时加上分号，使 js 语法符合预期

- paas-ce/lesscode/lib/server/controller/mock-data.js
> mock 接口返回总数字段

- paas-ce/lesscode/lib/client/src/components/dynamic-tag.vue
- paas-ce/lesscode/lib/server/controller/mock-data.js
> dynamic-tag 监听 value的变化

- paas-ce/lesscode/lib/client/src/views/system/index.vue
- paas-ce/lesscode/lib/server/controller/project.js
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/server/model/project.js
- paas-ce/lesscode/lib/server/utils/npm/index.js
> fix: 图标字号设置无效

- paas-ce/lesscode/lib/server/model/project.js
> fix: 优化复制项目路由的逻辑修复复制项目报错的问题

- paas-ce/lesscode/lib/client/src/components/render/row.vue
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/big-tree/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/free-layout/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/grid/extends.js
- paas-ce/lesscode/lib/server/model/page-code.js
- feat: grid 组件添加列边距属性配置 gutter
- big-tree 添加 selectable 属性
- 自由布局添加 margin,padding 配置
> feat: grid 组件添加列边距属性配置 gutter; big-tree 添加 selectable 属性;自由布局添加 margin,padding 配置

- paas-ce/lesscode/lib/client/src/components/variable/variable-select.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/strategy/remote-example.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/slot.vue
- 属性切换为变量方式时的增加数据示例
- Fixes #546
> feature: 属性切换为变量方式时的增加数据示例

- paas-ce/lesscode/lib/client/src/views/system/operation/index.vue
- paas-ce/lesscode/lib/client/src/views/system/operation/stats/export-button.vue
- paas-ce/lesscode/lib/client/src/views/system/operation/stats/project/dim-project.vue
> chore(运营统计): 调整图表的大小和导出sheetName可配置

- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/pagination/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/table/index.js
> update: 表格 pagination 配置优化

- paas-ce/lesscode/lib/client/src/components/render/component.vue
- paas-ce/lesscode/lib/client/src/components/render/free-layout.vue
- paas-ce/lesscode/lib/client/src/components/render/grid.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
> fix: 侧边栏收起后，快捷键失效，不能删除

- paas-ce/lesscode/lib/client/build/build-dll.js
- paas-ce/lesscode/lib/client/build/webpack.prod.conf.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/table/index.js
- paas-ce/lesscode/lib/server/project-template/project-init-code/lib/client/build/build-dll.js
- paas-ce/lesscode/lib/server/project-template/project-init-code/lib/client/build/webpack.prod.conf.js
- update: 表格 pagination 配置优化
- update: 构建 parallel 优化
> update: 表格 pagination 配置优化 && 构建 parallel 优化

- paas-ce/lesscode/lib/client/src/components/render/component.css
- paas-ce/lesscode/lib/client/src/components/render/free-layout.vue
- paas-ce/lesscode/lib/client/src/components/render/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/card/index.js
- paas-ce/lesscode/lib/server/controller/db-migration-helper.js
- paas-ce/lesscode/lib/server/util.js
- paas-ce/lesscode/package.json
1. 开放Card组件的foot、header插槽
2. 刷Page的旧Card数据
3. 关闭原Card组件的title属性
> feature: Card组件开发foot、header插槽

- paas-ce/lesscode/lib/server/middleware/auth.js
- paas-ce/lesscode/package.json
- feat: update axios version && add proxy config to axios
> feat: update axios version && add proxy config to axios

- paas-ce/lesscode/package.json
- feat: update nodejs & npm version
> feat: update nodejs & npm version

- paas-ce/lesscode/package.json
- feat: add @babel/plugin-transform-modules-commonjs
> feat: add @babel/plugin-transform-modules-commonjs

- paas-ce/lesscode/package.json
> feat: 生产模式支持

- paas-ce/lesscode/lib/client/src/components/field-table/field-table.tsx
- paas-ce/lesscode/lib/client/src/views/project/data-source-manage/table-design/create-table.vue
- paas-ce/lesscode/lib/client/src/views/project/data-source-manage/table-design/table-list/list/index.vue
- paas-ce/lesscode/lib/server/controller/project.js
> feat: 数据源管理 update

- paas-ce/lesscode/lib/client/src/views/project/page-setting.vue
- 尺寸、边距等层级统一放入页面样式设置
- 修改编辑状态的ui和交互
- Fixes #551
> optimization: 页面样式设置优化

- paas-ce/lesscode/lib/client/src/components/version-log.vue
- paas-ce/lesscode/lib/client/src/views/project/version-manage/children/form-sideslider.vue
- paas-ce/lesscode/lib/server/router/project-version.js
- paas-ce/lesscode/lib/server/service/project-version.js
> fix: 版本管理体验问题修复

- paas-ce/lesscode/lib/server/controller/layout.js
> fix: 修复布局模板判重问题

- paas2/paas/tpapp/views.py
- bugfix: tpapp info add paas_host
- Fixes #
> fix(tpapp): visiable lables app_info add paas_host

- paas-ce/lesscode/lib/client/src/components/project-version-selector.vue
- paas-ce/lesscode/lib/client/src/components/project/page-from-template-dialog.vue
- paas-ce/lesscode/lib/client/src/preview/index.js
- paas-ce/lesscode/lib/client/src/store/modules/project-version.js
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/lib/client/src/views/project/page.vue
- paas-ce/lesscode/lib/client/src/views/project/version-manage/children/form-sideslider.vue
- paas-ce/lesscode/lib/client/src/views/project/version-manage/index.vue
- paas-ce/lesscode/lib/client/src/views/system/components/template-dialog.vue
- paas-ce/lesscode/lib/client/src/views/system/projects.vue
- paas-ce/lesscode/lib/server/controller/project-version.js
- paas-ce/lesscode/lib/server/model/entities/project-version.js
- paas-ce/lesscode/lib/server/model/migrations/20211124155657-update-sql.js
- paas-ce/lesscode/lib/server/model/migrations/sqls/20211124155657-update-sql-down.sql
- paas-ce/lesscode/lib/server/model/migrations/sqls/20211124155657-update-sql-up.sql
- paas-ce/lesscode/lib/server/model/sql/20211124/update.sql
- paas-ce/lesscode/lib/server/router/project-version.js
- paas-ce/lesscode/lib/server/service/project-version.js
> feat: 新增项目版本归档功能

- paas-ce/lesscode/lib/client/src/views/project/page-setting.vue
- 修复页面样式设置取消，数据却变更的问题
- Fixes #551
> bugfix: 页面样式设置优化

- paas-ce/lesscode/lib/client/src/views/project/version-manage/index.vue
- paas-ce/lesscode/lib/server/service/project-version.js
> fix: 修改项目版本归档体验问题

- paas-ce/lesscode/lib/server/model/project-code.js
> fix: 支持默认跳转到布局中的第一个子路由

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/directives/index.vue
- paas-ce/lesscode/lib/client/src/views/project/data-source-manage/common/field-table.tsx
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/shared/data-source/data-parse/struct-parser/sql-parser.js
- paas-ce/lesscode/lib/shared/variable/constant.js
> 优化计算变量 & v-model 填值的情况

- paas-ce/lesscode/lib/client/src/element-materials/materials/element/table/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/strategy/table-data-source.vue
- element组件库 table组件支持数据源配置
- Fixes #656
> feature: element组件库 table组件支持数据源

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/styles/strategy/custom-style.vue
- paas-ce/lesscode/lib/client/src/views/project/page-setting.vue
> feature: 页面样式配置ui修改

- paas-ce/lesscode/lib/client/src/views/project/basic.vue
- paas-ce/lesscode/lib/client/src/views/project/index.vue
- paas-ce/lesscode/lib/client/src/views/system/index.vue
> fix: 导航滚动和收起样式优化

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/styles/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/action-bar/quick-operation.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- Fixes #
- fix: 修复粘贴触发4次的问题 & 属性面板错误提示问题
> fix: 修复粘贴触发4次的问题 & 属性面板错误提示问题

- paas-ce/lesscode/lib/client/src/element-materials/core/helper/commands.js
- paas-ce/lesscode/lib/client/src/element-materials/core/widget/menu.vue
- paas-ce/lesscode/lib/client/src/main.js
- paas-ce/lesscode/lib/client/src/views/index/components/action-bar/quick-operation.vue
- paas-ce/lesscode/lib/client/src/views/index/components/modifier-panel/index.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- update 删除、清空grid添加确认弹窗，判断是否是最后一个grid
> update: 删除、清空grid添加确认弹窗，判断是否是最后一个grid

- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/common/group-box/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/common/search-box/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/panel-component/components/render-base-component.vue
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/panel-component/components/render-custom-component.vue
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/panel-component/components/render-icon.vue
- 组件、自定义组件、icon左侧面板新增搜索功能
- Fixes #
> feature: 组件、icon左侧面板新增搜索功能

- paas-ce/lesscode/lib/client/src/views/index/index.vue
- fix: 修复选中组件并且收起侧边栏时,快捷键删除失效的问题
> fix: 修复选中组件并且收起侧边栏时,快捷键删除失效的问题

- paas2/esb/components/confapis/bk_log/bk_log.yaml
> up bk_log confapis

- paas-ce/lesscode/lib/client/src/views/index/components/operation-area/components/page-setting.vue
> feature: 页面样式配置代码补全

- paas2/paas/templates/home/index.html
> fix(console/index): fix contact_us tip

- paas-ce/lesscode/lib/client/src/element-materials/materials/README.md
> feature: 组件config说明文档修改

- paas-ce/lesscode/lib/client/src/preview/router.js
- paas-ce/lesscode/lib/client/src/views/index/index.vue
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/shared/util.js
- paas-ce/lesscode/lib/shared/variable/constant.js
- paas-ce/lesscode/package.json
> 1. 预览之前不需要保存 2. 优化函数和变量的生成

- paas2/esb/common/base_utils.py
- paas2/esb/esb/management/commands/export_official_api_docs.py
> fix export api docs

- paas-ce/lesscode/lib/client/src/element-materials/core/parse-data.js
- paas-ce/lesscode/lib/server/controller/db-migration-helper.js
> feature: 画布重构

- paas-ce/lesscode/lib/server/controller/db-migration-helper.js
> feature: 页面模板中card数据更新

- paas-ce/lesscode/lib/client/src/components/render/pc/resolve-component.vue
- paas-ce/lesscode/lib/client/src/element-materials/core/Node.js
- paas-ce/lesscode/lib/client/src/element-materials/core/helper/commands.js
- paas-ce/lesscode/lib/client/src/element-materials/core/parse-data.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/element/card/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/element/icon-list.js
- paas-ce/lesscode/lib/client/src/views/index/components/modifier-panel/index.vue
- paas-ce/lesscode/lib/server/controller/db-migration-helper.js
> 画布重构-Bug fix

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/styles/layout/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/styles/strategy/margin.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/styles/strategy/padding.vue
- padding margin增加重置按钮
- Fixes #
> feature: padding margin增加重置按钮

- paas-ce/lesscode/lib/client/src/element-materials/core/get-material.js
- paas-ce/lesscode/lib/client/src/element-materials/core/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/text.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/slot.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
> feature: 画布重构-体验问题

- paas-ce/lesscode/lib/client/src/components/project-version-selector.vue
- paas-ce/lesscode/lib/client/src/views/project/basic.vue
- paas-ce/lesscode/lib/client/src/views/project/index.vue
- paas-ce/lesscode/lib/client/src/views/project/version-manage/children/form-sideslider.vue
> fix: 优化项目版本选择器宽度和错误提示

- paas2/esb/components/esb_conf.py
- esb hide cc update_object_topo_graphics
> hide cc update_object_topo_graphics

- paas2/paas/.gitignore
- paas2/paas/app/utils.py
- paas2/paas/app_env/views.py
- paas2/paas/app_esb_auth/views.py
- paas2/paas/bk_iam/views.py
- paas2/paas/common/bk_iam.py
- paas2/paas/common/decorators.py
- paas2/paas/release/views.py
- paas2/paas/saas/manager.py
- paas2/paas/saas/models.py
- paas2/paas/saas/urls.py
- paas2/paas/saas/views.py
- paas2/paas/templates/base_center.html
- paas2/paas/templates/saas/list_table.part
from has_app_develop_permission_or_is_smart_admin to has_app_develop_or_smart_develop_permission
- smart 应用细粒度权限管控
- Fixes #
> feat(iam/decorator): update decorator to support both app and smart

- paas-ce/lesscode/lib/server/controller/data-source.js
- paas-ce/lesscode/lib/server/decorator/authorization/index.js
- paas-ce/lesscode/lib/server/model/project-code.js
- paas-ce/lesscode/lib/server/service/data-service.js
- paas-ce/lesscode/lib/server/service/preview-db-service.js
> 修改 data-service 写法

- paas-ce/lesscode/lib/client/src/common/vant.js
- paas-ce/lesscode/lib/client/src/components/render/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/navbar/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/pagination/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/tree-select/index.js
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/common/group-box/hacker.js
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/common/group-box/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/operation-area/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/page-list/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/preview-switch/index.vue
- paas-ce/lesscode/lib/client/src/views/index/index.vue
> fix: 修复移动端画布的若干bug

- paas-ce/lesscode/lib/server/controller/data-source.js
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/server/model/project-code.js
- paas-ce/lesscode/lib/server/project-template/project-init-code/lib/server/controller/data-source.js
- paas-ce/lesscode/lib/server/project-template/project-init-code/lib/server/service/data-service.js
- paas-ce/lesscode/lib/server/service/data-service.js
- paas-ce/lesscode/lib/server/service/preview-db-service.js
- paas-ce/lesscode/lib/shared/perm/constant.js
> 修改data-service的写法

- paas-ce/lesscode/lib/client/src/common/vant.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/button/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/cell/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/check-box-group/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/datetime-picker/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/field/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/icon/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/image/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/number-keyboard/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/password-input/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/picker/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/radio-group/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/rate/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/list/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/render-config/vant/index.js
- 新增组件
DatetimePicker
Field (需要icon)
NumberKeyborad(需要icon)
PasswordInput(需要icon)
Picker(需要icon)
Radio
Rate
- Fixes #774
> 新增mobile组件

- paas-ce/lesscode/lib/client/src/router/index.js
- paas-ce/lesscode/lib/client/src/views/system/index.vue
- paas-ce/lesscode/lib/client/src/views/system/platform-manage/index.vue
- paas-ce/lesscode/lib/client/src/views/system/platform-manage/project-member/index.vue
- paas-ce/lesscode/lib/client/src/views/system/platform-manage/shared-mixin.js
- paas-ce/lesscode/lib/client/src/views/system/platform-manage/table-list-mixin.js
> feature: 新增平台管理-项目成员页面

- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/radio-group/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/rate/index.js
- paas-ce/lesscode/lib/server/model/page-code.js
- vant组件新增v-model配置 
- Fixes #774
> feature: vant组件新增v-model配置

- paas2/login/templates/account/login_ce.html
> fix login contact us add style z-index

- paas-ce/lesscode/lib/client/src/common/vant.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/search/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/slider/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/stepper/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/steps/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/list/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/render-config/vant/index.js
> update: 添加移动端组件

- paas2/login/urls.py
> urls.py add i18n support

- paas2/login/templates/account/login.html
- paas2/login/templates/account/login_ce.html
- paas2/paas/templates/base.html
- 更新企业版登录/开发者中心footer
- Fixes #
> Ft ee footer

- paas2/esb/components/bk/apisv2/usermanage/usermanage_component.py
- 修复: esb代理用户管理接口时不去除username字段
- Fixes #
> fix(esb/usermanage): fix usermanage username missing after esb proxy

- paas2/login/bkauth/actions.py
> fix(login/auth_login): auth_login fail exception handler

- paas-ce/lesscode/lib/client/src/components/render/mobile/edit-area.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/index.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/preview-switch.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/simulator-area.vue
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/index.js
> bugfix: 移动端代码优化

- paas-ce/lesscode/lib/client/src/components/render/pc/widget/grid.vue
> perf: 编辑页面样式优化

- paas-ce/lesscode/lib/client/src/components/member-selector.vue
- paas-ce/lesscode/lib/client/src/store/modules/member.js
- paas-ce/lesscode/lib/client/src/views/project/index.vue
- paas-ce/lesscode/lib/client/src/views/system/platform-manage/project-member/index.vue
- paas-ce/lesscode/lib/server/controller/operation.js
- paas-ce/lesscode/lib/server/controller/user.js
- paas-ce/lesscode/lib/server/model/user.js
- paas-ce/lesscode/lib/server/router/user.js
> fix: 修复新增项目管理员会变成项目成员的bug

- paas-ce/lesscode/lib/client/src/views/system/platform-manage/project-member/index.vue
- paas-ce/lesscode/lib/client/src/views/system/platform-manage/shared-mixin.js
> fix: fix function name

- paas-ce/lesscode/lib/client/src/components/render/mobile/area.scss
- paas-ce/lesscode/lib/client/src/components/render/mobile/edit-area.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/index.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/preview-switch.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/simulator-area.vue
- paas-ce/lesscode/lib/client/src/element-materials/core/event.js
- paas-ce/lesscode/lib/client/src/element-materials/core/helper/decorator.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/image/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/styles/strategy/font.vue
- paas-ce/lesscode/lib/client/src/views/index/components/page-list/index.vue
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/shared/util.js
> bugfix: 修复移动端的若干问题和优化问题

- paas-ce/lesscode/lib/server/model/common.js
- paas-ce/lesscode/lib/server/model/page-comp.js
> fix: 修复项目版本条件错误导致未查询到页面自定义组件的问题

- paas-ce/lesscode/lib/client/src/preview/children/bk-error.vue
- paas-ce/lesscode/lib/client/src/preview/router.js
- paas-ce/lesscode/lib/server/model/page-code.js
- paas-ce/lesscode/lib/server/model/project-code.js
> 优化一个页面失败整个预览失败问题

- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/common/use-preview-img.js
- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/common/use-save.js
- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/preview.vue
> fix: 修复错误获取项目当前版本的问题

- paas-ce/lesscode/lib/server/controller/page.js
- paas-ce/lesscode/lib/server/service/variable.js
> fix: 修复新建版本在变量引用变量时关联数据的问题

- paas-ce/lesscode/lib/client/src/components/render/mobile/edit-area.vue
- paas-ce/lesscode/lib/client/src/components/render/mobile/index.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/components/lesscode-tools.vue
- paas-ce/lesscode/lib/client/src/views/index/components/draw-layout/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/operation-area/index.vue
> feature: 调整画布逻辑

- paas-ce/lesscode/lib/client/src/common/vant.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/cell/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/vant/tab/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/list/vant/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/render-config/vant/index.js
- paas-ce/lesscode/lib/client/src/views/project/page.vue
> bugfix: 修复列表进入预览404的问题 && 添加移动端组件

- paas-ce/lesscode/lib/client/src/views/project/data-source-manage/common/field-table.tsx
- paas-ce/lesscode/lib/client/src/views/project/data-source-manage/data-manage/render-data.vue
- paas-ce/lesscode/lib/server/service/online-db-service.js
- paas-ce/lesscode/lib/shared/data-source/constant.js
- paas-ce/lesscode/lib/shared/data-source/data-parse/struct-parser/sql-parser.js
- paas-ce/lesscode/lib/shared/data-source/helper.js
- paas-ce/lesscode/lib/shared/no-code/constant.js
- paas-ce/lesscode/lib/shared/no-code/helper.js
- paas-ce/lesscode/lib/shared/no-code/index.js
> 对接nocode数据源改动

- paas-ce/lesscode/lib/client/src/components/render/pc/resolve-component.vue
> perf: 画布优化

- paas-ce/lesscode/lib/client/src/preview/router.js
- paas-ce/lesscode/lib/server/controller/data-source.js
- paas-ce/lesscode/lib/server/model/project.js
- paas-ce/lesscode/lib/server/service/preview-db-service.js
> 复制项目的时候，复制表信息

- paas-ce/lesscode/lib/server/model/page-code.js
> bugfix: 修复存量数据中，出现vmode为undefined导致项目报错、无法预览等

- paas-ce/lesscode/lib/server/model/page-code.js
> bugfix: 修复v-model源码生成，类型判断错误的问题

- paas-ce/lesscode/lib/server/controller/data-source.js
- paas-ce/lesscode/lib/server/service/no-code.js
- paas-ce/lesscode/lib/server/service/preview-db-service.js
- paas-ce/lesscode/lib/shared/data-source/data-parse/data-parser/json-parser.js
- paas-ce/lesscode/lib/shared/data-source/data-parse/index.js
- paas-ce/lesscode/lib/shared/data-source/data-parse/struct-parser/json-parser.js
> 添加 新增 & 修复 nocode数据源服务

- paas-ce/lesscode/lib/server/service/no-code.js
> nocode async

- paas-ce/lesscode/lib/server/service/no-code.js
- paas-ce/lesscode/lib/shared/no-code/helper.js
- paas-ce/lesscode/lib/shared/no-code/index.js
> 对接nocode新增表服务

- paas-ce/lesscode/lib/client/src/App.vue
- paas-ce/lesscode/lib/client/src/components/header.vue
- paas-ce/lesscode/lib/client/src/components/home-header.vue
- paas-ce/lesscode/lib/client/src/main.js
> feat: 修改header

- paas-ce/lesscode/lib/client/src/views/home/index.vue
> feat: 新增gif cdn

- paas-ce/lesscode/lib/client/src/components/render/pc/widget/layout/components/complex.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/widget/layout/components/left-right.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/widget/layout/components/top-bottom.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/complex-side/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/complex-top/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/side-menu/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/template/top-menu/index.vue
> feature: 导航主题色体验优化

- paas-ce/lesscode/lib/client/src/components/home-header.vue
- paas-ce/lesscode/lib/client/src/components/loader/index.vue
- paas-ce/lesscode/lib/client/src/components/loader/loading/index.vue
- paas-ce/lesscode/lib/client/src/views/home/index.vue
> feat: 修改ui细节

- paas-ce/lesscode/lib/client/src/components/home-header.vue
- paas-ce/lesscode/lib/client/src/views/home/index.vue
> feat: 调整细节

- paas-ce/lesscode/lib/client/src/components/render/pc/widget/layout/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/core/static/is-layout-type.js
> hotfix: 页面最小宽度配置生效范围,表格配置不生效

- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/common/use-canvas-lock.js
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/panel-component/components/render-base-component.vue
> hotfix: 画布锁编辑状态显示不正确

- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/index.js
- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/common/use-canvas-lock.js
- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/save-canvas.vue
> hotfix: 画布锁

- paas-ce/lesscode/lib/client/src/store/modules/release.js
- paas-ce/lesscode/lib/client/src/views/project/release/history.vue
- paas-ce/lesscode/lib/client/src/views/project/release/index.vue
- paas-ce/lesscode/lib/client/src/views/project/release/publish.vue
- paas-ce/lesscode/lib/client/src/views/project/version-manage/index.vue
- paas-ce/lesscode/lib/server/controller/release.js
- paas-ce/lesscode/lib/server/model/entities/release-version.js
- paas-ce/lesscode/lib/server/model/migrations/20220516063846-update-sql.js
- paas-ce/lesscode/lib/server/model/migrations/sqls/20220516063846-update-sql-down.sql
- paas-ce/lesscode/lib/server/model/migrations/sqls/20220516063846-update-sql-up.sql
- paas-ce/lesscode/lib/server/model/sql/20220516/update.sql
> feat: 部署版本体验优化

- paas-ce/lesscode/lib/client/src/components/render/common/drag-line.js
- paas-ce/lesscode/lib/client/src/components/render/pc/components/draggable.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/index.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/resolve-interactive-component.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/hooks/use-component-active.js
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/hooks/use-component-hover.js
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/lesscode-focus/index.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/lesscode-resize/index.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/lesscode-tool/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/core/Node.js
- paas-ce/lesscode/lib/client/src/element-materials/core/static/create-node.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/card/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/dialog/index.js
- paas-ce/lesscode/lib/client/src/element-materials/materials/bk/sideslider/index.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/directives/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/slot.vue
- paas-ce/lesscode/lib/client/src/views/index/components/action-tool/components/quick-operation.vue
- paas-ce/lesscode/lib/client/src/views/index/components/material-panel/components/panel-tree/index.vue
- paas-ce/lesscode/lib/server/model/page-code.js
> hotfix: 画布体验问题

- paas-ce/lesscode/lib/server/model/page-code.js
> perf: 代码格式问题

- paas-ce/lesscode/lib/client/src/components/render/pc/components/draggable.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/resolve-component.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/hooks/use-component-active.js
- paas-ce/lesscode/lib/client/src/components/render/pc/tools/hooks/use-component-hover.js
- paas-ce/lesscode/lib/client/src/components/render/pc/widget/form.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/widget/layout/components/left-right.vue
- paas-ce/lesscode/lib/client/src/components/render/pc/widget/layout/index.vue
- paas-ce/lesscode/lib/client/src/element-materials/core/page-style.js
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/form/index.vue
> Feature container

- paas-ce/lesscode/lib/client/src/components/render-nocode/data-manage/index.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/data-manage/page-edit/buttonGroup.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/data-manage/page-edit/index.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/data-manage/page-edit/tableActionGroup.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/form/components/form-content/index.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/form/components/form-edit/dataSource/apiData.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/form/components/form-edit/fieldEdit.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/form/index.vue
- paas-ce/lesscode/lib/client/src/components/render-nocode/index.vue
- paas-ce/lesscode/lib/client/src/components/ui/extra-links.vue
- paas-ce/lesscode/lib/client/src/views/edit-nocode/index.vue
- paas-ce/lesscode/lib/client/src/views/index/components/draw-layout/index.vue
1.fix:修复eslint报错
2.feat:优化删除字段提示
3.feat:生成表单管理页
> feat:表单管理模块

- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
> perf: 表单项model属性配置

- paas-ce/lesscode/lib/client/src/components/choose-data-table.vue
- paas-ce/lesscode/lib/client/src/components/methods/choose-function/index.vue
- paas-ce/lesscode/lib/client/src/components/variable/variable-select/components/variable.vue
- paas-ce/lesscode/lib/client/src/element-materials/modifier/component/slots/components/select-data-source.vue
- paas-ce/lesscode/lib/client/src/views/project/data-source-manage/table-design/table-list/list/index.vue
> 函数和数据源提示优化

- paas-ce/lesscode/lib/client/src/components/render/pc/tools/lesscode-tool/hooks/use-save-template.js
> perf: 保存模板容器组件改为block

- paas-ce/lesscode/package.json
> update package.json scripts

- paas2/login/templates/account/login.html
- paas2/login/templates/account/login_ce.html
- 登录页密码显示和隐藏
- Fixes https://github.com/Tencent/bk-PaaS/issues/955
以下2个分支版本，已经有对应类似功能
open_paas 2.13.x/2.14.x (python3版本)
社区版 7.0 容器化版本
> feature:登录密码隐藏显示 #955

- paas-ce/lesscode/lib/client/src/components/render/pc/index.vue
> update: 交互式组件交互优化

- paas2/esb/components/confapis/monitor_v3/monitor_v3.yaml
- esb update monitor_v3 confapis
> up monitor_v3 confapis

- paas2/esb/components/confapis/monitor_v3/monitor_v3.yaml
> up monitor-v3 confapis

- readme.md
- readme_en.md
> 更新LessCode相关文档

- readme.md
- readme_en.md
> 更新LessCode相关文案

- paas2/login/templates/account/login_ce.html
> fix(login/footer): remove V6 from the footer

- paas2/esb/components/confapis/data/v3_queryengine.yaml
> update bk-data confapis

- readme.md
- readme_en.md
> docs: 更新导读文案

- paas2/paas/static/assets/components_vue/bk-user-selector.umd.js
> bugfix: 修复可见范围偶发报错 #1059

- paas2/paas/templates/saas/release/record.html
- 修复s-mart的saas初次部署失败时，发布记录不显示问题。
- Fixes #1076
> fixbug:s-mart初始部署异常时，发布记录显示问题 #1076

- paas2/esb/components/esb_conf.py
> change update_user_language to method GET, to support jsonp

- paas2/esb/components/confapis/bk_log/bk_log.yaml
> 更新 bklog confapis

- paas2/login/bkauth/forms.py
> Bugfix:登录页面只输入用户，点击登录后跳转到异常页面 #1105
